Iter13
kripsy/shortener pull request #17
Opened 2023-06-13 19:00 UTC by kripsy

2023-06-16 08:54 UTC, arttet requested changes, later dismissed

2023-06-16 08:54 UTC, arttet commented on Makefile
> +	go build -o ./cmd/shortener/shortener ./cmd/shortener/*.go
It would be better if you use `bin`

2023-06-16 08:54 UTC, arttet commented on descr.txt
> +run with db
Please use MD

2023-06-16 08:54 UTC, arttet commented on internal/app/db/db.go
> +	TABLESPACE pg_default;
Please don't use the PostgreSQL tables

2023-06-16 08:54 UTC, arttet commented on internal/app/db/db.go
> +	CREATE TABLE IF NOT EXISTS public.urls
Please add indexes

2023-06-19 14:11 UTC, kripsy commented on internal/app/db/db.go
> +	CREATE TABLE IF NOT EXISTS public.urls
done

2023-06-19 14:11 UTC, kripsy commented on internal/app/db/db.go
> +	TABLESPACE pg_default;
done

2023-06-19 14:11 UTC, kripsy commented on descr.txt
> +run with db
done

2023-06-19 14:11 UTC, kripsy commented on Makefile
> +	go build -o ./cmd/shortener/shortener ./cmd/shortener/*.go
done

2023-06-19 14:13 UTC, kripsy commented
in next sprints I'll
- change sql/database to pgxpool
- change insert via pgxtool
- add linter
- add db migrations

2023-06-19 18:41 UTC, kripsy commented
```
Добавь, пожалуйста, индексы и миграции. Не используй, таблицы Postgres
```
1) add bin directory
2) add indexes
3) add TODO list
4) add migrations
5) not using postgres table :)

2023-06-20 18:53 UTC, arttet approved these changes
Well done!

2023-06-20 18:53 UTC, arttet commented on README.md
> +Пример запуска локальных тестов
`Пример запуска тестов локально`

2023-06-20 18:53 UTC, arttet commented on internal/app/db/db.go
> +	CREATE TABLE IF NOT EXISTS public.urls
Why didn't you remove it?

2023-06-21 05:30 UTC, merged