Iter15
kripsy/shortener pull request #20
Opened 2023-06-27 12:44 UTC by kripsy

2023-07-01 07:02 UTC, arttet requested changes

2023-07-01 07:02 UTC, arttet commented on internal/app/utils/utils.go
> +// func for generation random short URL, consist of 5 bytes
Please look at comments in Go docs

2023-07-01 07:02 UTC, arttet commented on internal/app/db/db.go
> +			squirrel.Eq{"is_deleted": nil}}).
Please create a plan for this query.

2023-07-01 07:02 UTC, arttet commented on internal/app/handlers/handlers.go
> +	if splitstr[0] == "" {
What if this array is empty?

2023-07-01 07:02 UTC, arttet commented on internal/app/handlers/handlers.go
> +		err = h.repository.DeleteBatchURLFromStorage(ctx, splitstr, userID)
It is not batch

2023-07-03 12:44 UTC, kripsy commented on internal/app/db/db.go
> +			squirrel.Eq{"is_deleted": nil}}).
```
urls=# EXPLAIN UPDATE urls SET is_deleted = True WHERE (short_url IN (
'f3d35c9c5d281ee74f2d519c62ef276e',
'88b8173eae5c008c1ffd35284f35eafe',
'cd14884494e02fc279373b8c683c82c0'
) AND user_id = 463 AND is_deleted IS NULL);
                                                                          QUERY PLAN                                                                          
--------------------------------------------------------------------------------------------------------------------------------------------------------------
 Update on urls  (cost=12.02..23.95 rows=1 width=89)
   ->  Bitmap Heap Scan on urls  (cost=12.02..23.95 rows=1 width=89)
         Recheck Cond: (short_url = ANY ('{f3d35c9c5d281ee74f2d519c62ef276e,88b8173eae5c008c1ffd35284f35eafe,cd14884494e02fc279373b8c683c82c0}'::text[]))
         Filter: ((is_deleted IS NULL) AND (user_id = 463))
         ->  Bitmap Index Scan on urls_short_url_key  (cost=0.00..12.02 rows=3 width=0)
               Index Cond: (short_url = ANY ('{f3d35c9c5d281ee74f2d519c62ef276e,88b8173eae5c008c1ffd35284f35eafe,cd14884494e02fc279373b8c683c82c0}'::text[]))
(6 rows)
```

2023-07-03 13:09 UTC, kripsy commented on internal/app/utils/utils.go
> +// func for generation random short URL, consist of 5 bytes
1) fix in urils.
2) add task in "TO DO"

2023-07-03 13:22 UTC, kripsy commented on internal/app/handlers/handlers.go
> +	if splitstr[0] == "" {
If array empty - it returns 400.

2023-07-03 13:29 UTC, kripsy commented on internal/app/handlers/handlers.go
> +		err = h.repository.DeleteBatchURLFromStorage(ctx, splitstr, userID)
Rename to DeleteURLSliceFromStorage

2023-07-04 18:28 UTC, arttet approved these changes

2023-07-04 18:28 UTC, arttet commented on internal/app/db/db.go
> +	const migrationsPath = "./db/migrations"
It should be a parameter.

2023-08-09 11:17 UTC, merged