Iter20
kripsy/shortener pull request #28
Opened 2023-09-04 23:29 UTC by kripsy

2023-09-05 23:25 UTC, kripsy commented
@arttet написал, что оставил комменты в pr, но я не вижу комментариев))

2023-09-06 03:26 UTC, arttet requested changes

2023-09-06 03:26 UTC, arttet commented on .github/workflows/codecov.yml
> +name: Codecov
Please look at it 
https://app.codecov.io/github/kripsy/shortener/commit/f1b0420c00ddcbb35873fe2ed44cdcf21379f2da

It seems sth is wrong.
We should get a report.
https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/

2023-09-06 03:26 UTC, arttet commented on README.md
> +go run -ldflags "-X main.buildVersion=1.0 -X main.buildDate=2023/09/05 -X main.buildCommit=asdfg" ./cmd/shortener/main.go -l "Debug"
It should be a hash code. Please use `git` and `bash`

2023-09-06 03:26 UTC, arttet commented on cmd/staticlint/main.go
> +		if strings.Contains(pass.Fset.Position(file.Pos()).Filename, "/Library/Caches/go-build/") {
What about other platforms?

2023-09-06 03:26 UTC, arttet commented on .github/workflows/golangci-lint.yml
> +      - name: golangci-lint
Let's enable all linters:)

2023-09-06 08:13 UTC, kripsy commented on .github/workflows/codecov.yml
> +name: Codecov
it seems was a bug. after retrying job code devtable with test coverage was mentioned in comment

2023-09-06 08:23 UTC, kripsy commented on README.md
> +go run -ldflags "-X main.buildVersion=1.0 -X main.buildDate=2023/09/05 -X main.buildCommit=asdfg" ./cmd/shortener/main.go -l "Debug"
add hash from branch, add date with format.

2023-09-06 08:35 UTC, kripsy commented on cmd/staticlint/main.go
> +		if strings.Contains(pass.Fset.Position(file.Pos()).Filename, "/Library/Caches/go-build/") {
Поправил. Теперь фильтрую файлы по комментарию "// Code generated .* DO NOT EDIT"

2023-09-06 14:25 UTC, kripsy commented on .github/workflows/golangci-lint.yml
> +      - name: golangci-lint
сделал. единственное - исключил некоторые линтеры, в некоторых участках кода исключил проверку на конструкции, которые посчитал минорными.

2023-09-07 06:35 UTC, arttet approved these changes

2023-09-07 06:35 UTC, arttet commented on internal/app/application/application.go
> +func NewApp(_ context.Context) (*App, error) {
```suggestion
func NewApp(ctx context.Context) (*App, error) {
```

2023-09-07 06:35 UTC, arttet commented on internal/app/application/application.go
> +		db, err = database.InitDB(context.Background(), cfg.DatabaseDsn, myLogger)
```suggestion
		db, err = database.InitDB(ctx, cfg.DatabaseDsn, myLogger)
```

2023-09-07 09:24 UTC, merged