Iter23
kripsy/shortener pull request #32
Opened 2023-09-19 14:58 UTC by kripsy

2023-09-19 17:30 UTC, kripsy commented
@arttet 
не успел разобраться почему не отображается репорт от codecover.
завтра разберусь, сейчас просто отправлю ссылку, чтобы практикум посчитал закрытие спринта.

2023-09-20 10:59 UTC, kripsy commented
@arttet поправил codecover))

2023-09-22 15:38 UTC, arttet requested changes

2023-09-22 15:38 UTC, arttet commented on .gitignore
> +pki/*.crt
Maybe cert?
```suggestion
cert/*.crt
```

2023-09-22 15:38 UTC, arttet commented on cmd/shortener/main.go
> +		fmt.Println("CREATE CERT")
It would be better if it is debug log

2023-09-22 15:38 UTC, arttet commented on cmd/shortener/main.go
> +		err = srv.ListenAndServeTLS("./pki/server.crt", "./pki/server.key")
This is a magic string

2023-09-22 15:38 UTC, arttet commented on cmd/shortener/main.go
> +		if err := srv.Shutdown(context.Background()); err != nil {
Please use context with timeout

2023-09-22 15:38 UTC, arttet commented on cmd/shortener/main.go
> +func createCertificate() error {
It should not be in `main`

2023-09-22 15:38 UTC, arttet commented on internal/app/logger/logger_test.go
> +//nolint:testpackage
Why?

2023-09-22 15:38 UTC, arttet commented on internal/app/config/config.go
> +		//nolint:nestif
This is a good point

2023-09-22 15:38 UTC, arttet commented on cmd/shortener/main.go
> +		IdleTimeout: 30 * time.Second,
This is a magic number

2023-09-25 08:24 UTC, kripsy commented on .gitignore
> +pki/*.crt
fixed

2023-09-25 08:24 UTC, kripsy commented on cmd/shortener/main.go
> +		fmt.Println("CREATE CERT")
fixed

2023-09-25 08:24 UTC, kripsy commented on cmd/shortener/main.go
> +		err = srv.ListenAndServeTLS("./pki/server.crt", "./pki/server.key")
fixed

2023-09-25 08:24 UTC, kripsy commented on cmd/shortener/main.go
> +		if err := srv.Shutdown(context.Background()); err != nil {
fixed

2023-09-25 08:24 UTC, kripsy commented on internal/app/logger/logger_test.go
> +//nolint:testpackage
fixed for all tests

2023-09-25 08:24 UTC, kripsy commented on cmd/shortener/main.go
> +		IdleTimeout: 30 * time.Second,
fixed

2023-09-25 08:25 UTC, kripsy commented on internal/app/config/config.go
> +		//nolint:nestif
I wasn't be sure about this. imho))

2023-09-25 08:28 UTC, kripsy commented on cmd/shortener/main.go
> +func createCertificate() error {
fixed

2023-09-25 09:18 UTC, kripsy commented
@arttet doooooneeee 🫡

2023-09-26 07:55 UTC, kripsy commented
@arttet smth anything else?))

2023-09-26 07:59 UTC, arttet commented
> @arttet smth anything else?))

Please create a ticket

2023-09-26 11:07 UTC, kripsy commented
> > @arttet smth anything else?))
> 
> Please create a ticket

Ticket about what?
Linters? I don't think that warning is a some mistake in product. It's all my responsibility, because I edit config and enable all linters.

2023-09-26 11:11 UTC, arttet commented
> > > @arttet smth anything else?))
> > 
> > Please create a ticket
> 
> Ticket about what?
> Linters? I don't think that warning is a some mistake in product. It's all my responsibility, because I edit config and enable all linters.

Please create a ticket in the tracking system.

2023-09-26 12:23 UTC, kripsy commented
> > > > @arttet smth anything else?))
> > > 
> > > 
> > > Please create a ticket
> > 
> > 
> > Ticket about what?
> > Linters? I don't think that warning is a some mistake in product. It's all my responsibility, because I edit config and enable all linters.
> 
> Please create a ticket in the tracking system.

I hope you mean a new ticket for checking my task in the Yandex prakticum.)) 🤔

2023-09-26 16:10 UTC, arttet approved these changes

2023-09-26 16:10 UTC, arttet commented on Makefile
> +.PHONY: run_unittest
Maybe: `test` ?

2023-09-26 16:10 UTC, arttet commented on Makefile
> +.PHONY: run_unittest
```suggestion
.PHONY: test
```

2023-09-26 16:10 UTC, arttet commented on codecov.yml
> +coverage:
```suggestion
coverage:
  range: 80..100
  round: down
  precision: 2
```

2023-09-26 19:38 UTC, kripsy commented
@arttet u didn't accept in tracking my task)) pls accept it in Yandex practikum))

2023-10-01 09:34 UTC, merged